[tool.poetry]
name = "docker-homework-1"
version = "0.1.0"
description = "ДЗ Docker"
authors = ["DarkhanDaurenov <takishevdarkhan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
